apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type:
    LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 4200
      protocol: TCP
      targetPort: 4200
      nodePort: 30010
